API.md
README.md

chore: add badge to README

---

README.md

chore: make the README better

---

API.md
src/aurora.activity-stream.ts
src/aurora.ts
src/helpers.ts
test/aurora.activity-stream.get-cluster-arn.test.ts
test/aurora.activity-stream.is-complete.test.ts
test/aurora.activity-stream.methods.test.ts
test/aurora.activity-stream.on-event.test.ts
test/aurora.test.ts

feat: activityStreams option

---

src/aurora.provisioner.ts
src/aurora.ts
test/aurora.provisioner.methods.test.ts

- feat: add proxyHost entry to user secrets
- ProxyEndpoint output should only exist if we are creating a proxy
Fixes #

feat: add proxyHost to reader/writer secrets

---

API.md
src/aurora.provisioner.ts
src/aurora.ts
test/aurora.provisioner.handler.test.ts
test/aurora.provisioner.methods.test.ts
test/aurora.test.ts

feat: onUpdate support

---

API.md
src/aurora.ts

feat: Expose security group

---

API.md
src/aurora.provision-database.ts
src/aurora.provision-user.ts
test/aurora.provision-database.methods.test.ts
test/aurora.provisioner-user.methods.test.ts

fix: explicitly conform settings

---

API.md
src/aurora.ts
test/aurora.test.ts

allow specifiying multiple security groups for aurora cluster.

feat: allow passing multiple security groups [CLK-126702]

---

API.md
src/aurora.ts
test/aurora.test.ts

- chore: refactor tests
- feat: secretPrefix support for secret names

feat: secretPrefix support for secret names

---

src/aurora.provision-database.ts
src/aurora.provision-user.ts

But... WHY does the connection fail?

fix: even more logging

---

API.md
src/aurora.ts
test/aurora.test.ts

Also addresses sneaky timing / implicit bug.

fix: skipDb should also skipUser

---

test/aurora.test.ts

- refactor VPC config
- chore: provide test for default vpcSubnets

chore: test default vpcSubnet

---

src/aurora.provision-database.ts
src/helpers.ts
test/aurora.provision-database.methods.test.ts

fix: Use different mocking method for retry waits

---

src/aurora.provision-database.ts
src/aurora.ts
src/helpers.ts
test/aurora.provision-database.handler.test.ts
test/aurora.provision-database.methods.test.ts

Fixes #35 
- refactor tests to localize stubbing
- feat: db provisioner retries connect

feat: db provisioner retries connect

---

API.md
src/aurora.ts
test/aurora.test.ts

I haven't tested to confirm that the default file is actually `postgresql`, but that's what it says in the docs. When I look at the console, it looks like `error/postgresql.log`, but... ??? This needs integration testing.

feat: support log publishing

---

API.md
src/aurora.ts
test/aurora.test.ts

https://github.com/aws/aws-cdk/pull/25347 to fix the gap here. Kinda shocking. Until it's through, we'll do some magical casting hackery.

feat: performanceInsights

---

API.md
src/aurora.ts
test/aurora.test.ts

Changes:
- Add secret rotation interval config defaulted to 90 days

feat: add aurora password rotation interval config [CLK-250941]

---

src/aurora.provision-database.ts
test/aurora.provision-database.handler.test.ts
test/aurora.provision-database.methods.test.ts

feat: re-fetch secret if connect fails with 'password authentication failed'

---

src/aurora.ts

aws-cdk-lib has advanced far past this pin: https://github.com/aws/aws-cdk/blob/1fd22a7498223ae5d2faf1799056e81be4f71f5c/packages/aws-cdk-lib/aws-secretsmanager/lib/secret-rotation.ts#L63

fix: unpin SAR mappings [CLK-340743]

---

.projen/deps.json
.projenrc.ts
API.md
package.json
pnpm-lock.yaml
src/aurora.ts
test/aurora.test.ts

switch to rolling update by default

feat!: update default to 15.5
